name: Build ServEcosys ISO
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test with spaces
        run: |
          mkdir -p "root project/build"
          echo hello > "root project/build/test.txt"
          ls -la "root project/build/"